# Different fss' total LOC in different versions.

In [1]:
import pandas as pd
from pandas import DataFrame

In [2]:
linux_version = ["linux-2.6"]
for i in range(20):
    term = "linux-3."+str(i)
    linux_version.append(term)
for i in range(17):
    term = "linux-4."+str(i)
    linux_version.append(term)

In [3]:
linux_version

['linux-2.6',
 'linux-3.0',
 'linux-3.1',
 'linux-3.2',
 'linux-3.3',
 'linux-3.4',
 'linux-3.5',
 'linux-3.6',
 'linux-3.7',
 'linux-3.8',
 'linux-3.9',
 'linux-3.10',
 'linux-3.11',
 'linux-3.12',
 'linux-3.13',
 'linux-3.14',
 'linux-3.15',
 'linux-3.16',
 'linux-3.17',
 'linux-3.18',
 'linux-3.19',
 'linux-4.0',
 'linux-4.1',
 'linux-4.2',
 'linux-4.3',
 'linux-4.4',
 'linux-4.5',
 'linux-4.6',
 'linux-4.7',
 'linux-4.8',
 'linux-4.9',
 'linux-4.10',
 'linux-4.11',
 'linux-4.12',
 'linux-4.13',
 'linux-4.14',
 'linux-4.15',
 'linux-4.16']

In [4]:
fss = ['ext3', 'ext4', 'xfs', 'jfs', 'btrfs', 'reiserfs']

In [5]:
LOC = DataFrame(index=fss,columns=linux_version).fillna(0)

In [6]:
LOC.index

Index(['ext3', 'ext4', 'xfs', 'jfs', 'btrfs', 'reiserfs'], dtype='object')

In [7]:
for i in linux_version:
    print(i)
    file = open("..\\kernel\\"+i+"\\file_size.txt")
    filelines = file.readlines()
    for line in filelines:

        fs = line.split("/")[0]
        try:
            loc = int(line.split()[-2])
            LOC.loc[fs][i]+=loc
        except:
            print(i)
            print(line.split())

linux-2.6
linux-3.0
linux-3.1
linux-3.2
linux-3.3
linux-3.4
linux-3.5
linux-3.6
linux-3.7
linux-3.8
linux-3.9
linux-3.10
linux-3.11
linux-3.12
linux-3.13
linux-3.14
linux-3.15
linux-3.16
linux-3.17
linux-3.18
linux-3.19
linux-4.0
linux-4.1
linux-4.2
linux-4.3
linux-4.4
linux-4.5
linux-4.6
linux-4.7
linux-4.8
linux-4.9
linux-4.10
linux-4.11
linux-4.12
linux-4.13
linux-4.14
linux-4.15
linux-4.16

In [8]:
LOC

,linux-2.6,linux-3.0,linux-3.1,linux-3.2,linux-3.3,linux-3.4,linux-3.5,linux-3.6,linux-3.7,linux-3.8,...,linux-4.7,linux-4.8,linux-4.9,linux-4.10,linux-4.11,linux-4.12,linux-4.13,linux-4.14,linux-4.15,linux-4.16
ext3,32275,16944,17017,17047,16960,18269,18282,18265,18300,18296,...,0,0,0,0,0,0,0,0,0,0
ext4,35721,36743,36899,38633,38491,38768,39696,39897,40516,43589,...,50793,49147,49305,49452,49691,50681,52389,52493,52211,52126
xfs,74780,75230,96929,96749,95464,94837,94433,94616,95053,96635,...,60660,62372,69267,67806,68036,69090,69404,69606,69500,69707
jfs,32835,32850,32787,32803,32785,32793,32778,32783,33149,33159,...,33022,33018,33011,33012,33012,33066,33071,33069,33074,33069
btrfs,62942,65337,65290,70065,75566,77926,80015,88185,90233,94149,...,119207,120256,120870,120735,120955,121655,122069,123054,124688,125456
reiserfs,27881,27926,27836,27920,30931,28114,31145,31192,31211,31218,...,32600,32596,32602,32591,32591,32636,32643,32650,32654,32646

In [9]:
modify_len = DataFrame(index=fss,columns=linux_version).fillna(0)

In [10]:
modify_len

,linux-2.6,linux-3.0,linux-3.1,linux-3.2,linux-3.3,linux-3.4,linux-3.5,linux-3.6,linux-3.7,linux-3.8,...,linux-4.7,linux-4.8,linux-4.9,linux-4.10,linux-4.11,linux-4.12,linux-4.13,linux-4.14,linux-4.15,linux-4.16
ext3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ext4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
xfs,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
jfs,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
btrfs,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
reiserfs,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
for i in linux_version:
    for j in fss:
        try:
            file = open("..\\kernel\\"+i+"\\"+j+"\\"+j+"-patches.txt")
        except:
            print(i+j)
            print("There is no document")
        filelines = file.readlines()
        for line in filelines:
            if((line[0]=='+'and line[1]!='+' ) or (line[0]=='-' and line[0]!='-')):
                modify_len.loc[j][i]+=1

linux-2.6ext4
There is no document
linux-2.6xfs
There is no document
linux-2.6jfs
There is no document
linux-2.6btrfs
There is no document
linux-2.6reiserfs
There is no document
linux-3.1jfs
There is no document
linux-3.1btrfs
There is no document
linux-3.3ext3
There is no document
linux-3.3xfs
There is no document
linux-3.3jfs
There is no document
linux-3.3reiserfs
There is no document
linux-3.5xfs
There is no document
linux-3.5jfs
There is no document
linux-3.5reiserfs
There is no document
linux-3.6ext3
There is no document
linux-3.6jfs
There is no document
linux-3.6btrfs
There is no document
linux-3.7ext3
There is no document
linux-3.7jfs
There is no document
linux-3.7btrfs
There is no document
linux-3.7reiserfs
There is no document
linux-3.8jfs
There is no document
linux-3.11reiserfs
There is no document
linux-3.13ext3
There is no document
linux-3.13jfs
There is no document
linux-3.13reiserfs
There is no document
linux-3.14jfs
There is no document
linux-3.15ext3
There is no document
linux-3.15jfs
There is no document
linux-3.17jfs
There is no document
linux-3.17reiserfs
There is no document
linux-3.18ext3
There is no document
linux-3.19ext3
There is no document
linux-3.19jfs
There is no document
linux-3.19reiserfs
There is no document
linux-4.0ext3
There is no document
linux-4.0jfs
There is no document
linux-4.0reiserfs
There is no document
linux-4.2ext3
There is no document
linux-4.2xfs
There is no document
linux-4.2jfs
There is no document
linux-4.2reiserfs
There is no document
linux-4.3ext3
There is no document
linux-4.3xfs
There is no document
linux-4.3jfs
There is no document
linux-4.3reiserfs
There is no document
linux-4.4ext3
There is no document
linux-4.5ext3
There is no document
linux-4.5jfs
There is no document
linux-4.5reiserfs
There is no document
linux-4.6ext3
There is no document
linux-4.6jfs
There is no document
linux-4.6reiserfs
There is no document
linux-4.7ext3
There is no document
linux-4.7jfs
There is no document
linux-4.8ext3
There is no document
linux-4.9ext3
There is no document
linux-4.10ext3
There is no document
linux-4.10jfs
There is no document
linux-4.10reiserfs
There is no document
linux-4.11ext3
There is no document
linux-4.11jfs
There is no document
linux-4.12ext3
There is no document
linux-4.13ext3
There is no document
linux-4.13jfs
There is no document
linux-4.13reiserfs
There is no document
linux-4.14ext3
There is no document
linux-4.15ext3
There is no document
linux-4.15jfs
There is no document
linux-4.15reiserfs
There is no document
linux-4.16ext3
There is no document

In [12]:
modify_len

,linux-2.6,linux-3.0,linux-3.1,linux-3.2,linux-3.3,linux-3.4,linux-3.5,linux-3.6,linux-3.7,linux-3.8,...,linux-4.7,linux-4.8,linux-4.9,linux-4.10,linux-4.11,linux-4.12,linux-4.13,linux-4.14,linux-4.15,linux-4.16
ext3,2,45,21,190,0,149,14,0,0,2,...,0,0,0,0,0,0,0,0,0,0
ext4,0,265,32,1528,5,856,133,170,42,123,...,132,120,449,186,86,23,33,205,13,160
xfs,0,430,54,189,0,55,0,34,58,93,...,16,7,2946,506,268,17,844,238,2,16
jfs,0,26,0,34,0,29,0,0,0,0,...,0,2,14,0,0,8,0,4,0,4
btrfs,0,83,0,665,75,256,2,0,0,215,...,154,341,301,6,12,42,30,673,177,201
reiserfs,0,80,16,146,0,73,0,62,0,2,...,13,13,43,0,2,7,0,5,0,5